version: '0.2'
phases:
  install:
    runtime-versions:
      nodejs: 18.20.4
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo ID_ntZChZy9
      - echo Creating zip archive of the application...
      - tar -czvf PLN5000243.tar.gz *
  post_build:
    commands:
      - echo Build completed. Artifacts are ready for deployment.
artifacts:
  files:
    - PLN5000243.tar.gz
